language: python

services:
  - postgresql
addons:
  postgresql: "9.6"

python:
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install python-coveralls

before_script:
  - psql -c "create user husky with password 'husky' createdb;" -U postgres
  - psql -c "create database husky;" -U postgres
script: 
  - coverage run manage.py test
after_success:
  - coveralls