# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 19:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20171128_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='answers',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
