# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 07:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0003_quizresult_answers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizresult',
            unique_together=set([('quiz', 'user')]),
        ),
    ]
